# Generated by Django 2.2.5 on 2020-01-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='draw',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='p1',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='p2',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
