# Generated by Django 2.2.5 on 2020-01-08 05:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.IntegerField(null=True)),
                ('grid', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None), null=True, size=None)),
                ('pos1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('pos2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('nbTurns', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('idNode', models.AutoField(primary_key=True, serialize=False)),
                ('typeNode', models.CharField(max_length=20, null=True)),
                ('up', models.IntegerField(null=True)),
                ('down', models.IntegerField(null=True)),
                ('left', models.IntegerField(null=True)),
                ('right', models.IntegerField(null=True)),
                ('p1', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('p2', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('draw', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
            ],
        ),
    ]
