# Generated by Django 2.2.5 on 2020-08-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200815_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='p1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='board.Player'),
        ),
        migrations.AddField(
            model_name='board',
            name='p2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='board.Player'),
        ),
    ]
