# Generated by Django 2.2.5 on 2020-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200816_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AddField(
            model_name='state',
            name='board_size',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='reward',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.CharField(default=-1, max_length=40, primary_key=True, serialize=False),
        ),
    ]
