# Generated by Django 2.2.5 on 2020-08-16 14:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200816_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None), null=True, size=None)),
                ('discovery_rate', models.FloatField(default=1.0, null=True)),
                ('learning_rate', models.FloatField(default=1.0, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='board.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AI', to='board.AI'),
        ),
    ]
